apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-deployment
  labels:
    app: node-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-todo
  template:
    metadata:
      labels:
        app: node-todo
    spec:
      containers:
      - name: node-todo
        image: gajananbarure/gajanan-node-todo-app
        ports:
        - containerPort: 8000
