apiVersion: v1
kind: Service
metadata:
  name: node-todo-service
  labels:
    app: node-todo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30007
  selector:
    app: node-todo
